title: Default
sections:
  main:
    display: Main
    fields:
      title:
        type: text
        width: 66
        localizable: true
      seo:
        type: partial
        fieldset: seo
      slug:
        type: text
        width: 33
      content:
        type: markdown
        display: Content
        localizable: true
taxonomies: true
